### ISSUE TITLE
description of \dXXX and \cXXX are reversed

### ISSUE THREAD

**Issue by u-fischer** [antoinelejay/currency#1]
The documentation says that \dXXX has only an option argument and \cXXX an optional argument and a mandatory argument for the value but actually it is the other way round:

```
\documentclass[]{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}
\usepackage[T1]{fontenc}
\usepackage{currency}

\sisetup{locale=DE}

\begin{document}

\DefineCurrency{EUR}{iso={EUR},symbol=\euro,kind=iso}

\cEUR xxx \dEUR{1.2} \num{1.2}

\end{document}
```
(it would be good if there were some mnemonic for the naming.  I personally would prefer e.g. \cvXXX (currency value) or \nXXX (\n for number) or \vXXX (\v for value) for the variant with a value.)

**Comment by antoinelejay** [comment]
This has been corrected in v0.2 just published, with an alias \vXXX for \dXXX
