### ISSUE TITLE
Space between $ and value

### ISSUE THREAD

**Issue by khatchad** [antoinelejay/currency#5]
I can't seem to figure out how to get rid of the space between `$` and the value for USD:
```tex
\DefineCurrency{USD}{name={dollar},plural={dollars},iso={USD},kind=symbol,symbol={\$},pre}
\dUSD{500000}
```
Gives `$ 500,000` but I want is `$500,000`.

**Comment by antoinelejay** [comment]
There is a pre-between key, by default set to ~


\DefineCurrency{USD}{name={dollar},plural={dollars},iso={USD},kind=symbol,symbol={\$},pre, pre-between={}}

Best regards
Antoine Lejay

**Comment by khatchad** [comment]
Just what I was looking for, thanks!
