### ISSUE TITLE
Error on non numerical value

### ISSUE THREAD

**Issue by JeT76-ESCP** [antoinelejay/currency#8]
Hi,

I'm integrating your package in my finance courses and keys make things so easy. Merci !

How can I input a non numerical value ?

I need 2^{n} EUR :)

```
\documentclass{article}
\usepackage{currency}
\usepackage{siunitx}
\usepackage{xcolor}

\DefineCurrency{EUR}{
	name={euro}, 
	plural={euros}, 
	symbol={\euro}, 
	iso={EUR}, 
	kind=iso,
}

\begin{document}

\dEUR{10}

$\dEUR{2^{n}}$

\dEUR{$2^{n}$}

\end{document}
```

**Comment by antoinelejay** [comment]
hello,

there is a key number=false to avoid parsing numbers. Actually,
you have access to the key-value pairs of siunitx as this package is used internally to print numbers and the key ‘ number’ corresponds to ‘parsing-numbers’ in siunitx.

best regards 
Antoine
