### ISSUE TITLE
Font specification does not apply to the monetary amount

### ISSUE THREAD

**Issue by maxpowis** [antoinelejay/currency#9]
I have a document with montserrat font applied as 

```latex
\usepackage{fontspec}
\setmainfont{montserrat}
\setsansfont{montserrat}
\setmonofont{montserrat}
```

However only the monetary amounts displayed with the currency package do not follow that font specification.

Hereafter a snippet that show the issue where the font is applied to the monetary symbol but not the numbers:

```latex
%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

\documentclass[10pt, a4paper]{beamer}

\usepackage{xunicode}
\usepackage{fontspec}

\usepackage{currency}
\DefineCurrency{EUR}{name={euro}, plural={euros}, symbol={\texteuro}, iso={EUR}, kind=iso, base=2}
\DefineCurrency{USD}{name={dollar}, plural={dollars}, symbol={\textdollar}, iso={USD}, kind=iso, base=2}
\CurrencySetup{kind=symbol}

\begin{document}

Symbol font changes but not the font of the number \\
\dEUR{4.2} = \dUSD{4.97} \\
\dEUR[font=\fontspec{Montserrat}]{4.2} = \dUSD[font=\fontspec{Montserrat}]{4.97} \\
\dEUR[font=\fontspec{montserrat}]{4.2} = \dUSD[font=\fontspec{montserrat}]{4.97}

\end{document}
```

Herafter a screenshot of the output compiled with xetex:

![image](https://github.com/antoinelejay/currency/assets/5753607/4b4c0237-0ef4-4b1d-9890-0a5896a557d4)

**Comment by antoinelejay** [comment]
The package relies on **siunitx** so that this is feature of this package to have possibly different font for the figures and for the units. You may use _e.g._ mode=text (see the siunitx documentation at Section 4.2):

\CurrencySetup{kind=symbol,mode=text}

**Comment by maxpowis** [comment]
Thanks for the answer. Works perfectly with that adaptation. Now sure how well it was documented because I have tried lots of options before creating this issue.

**Comment by antoinelejay** [comment]
Dear Max, 

yes, sorry if the doc is unclear. By the way, currency relies on siunitx and this package has been subject to many releases. 
In particular, I think that the option I gave you is actually rather recent, in any ways posterior to the currency package. 

Best regards
Antoine
